### ISSUE TITLE
create blackbox test for the api

### ISSUE THREAD

**Issue by renickbuettner** [renickbuettner/toolchain#31]
- [ ] test GET, POST, PUT, DELETE

https://blog.pusher.com/tests-laravel-applications/

**Comment by zumpious** [comment]
Also die ersten Tests laufen durch, weswegen ich der Meinung bin, dass der durch Reflections angelegte angelegte Nutzer funktioniert. Den nächsten Schritt, nämlich das assertJson schlägt jedoch fehl. Ich glaube ich bin einfach nicht in der lLage den Response Content an der richtigen Stelle auszulesen
