### ISSUE TITLE
RegEx fehlerhaft in serviceEditor.js (trz. low prio)

### ISSUE THREAD

**Issue by zumpious** [renickbuettner/toolchain#44]
Die RegEx sind nicht ganz korrekt
Es wird immer der vorletzte Buchstabe eingelesen und nicht der aktuelle

**Comment by renickbuettner** [comment]
Browser events: onKeyPress, onChange
Das ist so richtig, wenn du aus dem Feld rausklickst, wird onChange getriggert, ansonsten das keyPress event.
